## To execute this docker-compose yml file use 'docker-compose -f <file_name> up'
##Add the '-d' flag at the end for detached execution
#version: "3.8"
#services:
#  selenium-hub:
#    image: selenium/hub:4.30.0
#    container_name: selenium-hub
#    ports:
#      - "4444:4444"
#    environment:
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#    restart: always
#
#  chrome:
#    image: selenium/node-chrome:4.30.0
#    container_name: chrome-node
#    shm_size: "2gb"
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_SESSIONS=5
#      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
#    volumes:
#      - /dev/shm:/dev/shm
#    restart: on-failure:3
#
#  chrome_79:
#    image: selenium/node-chrome-debug:3.141.59-zinc
#    container_name: chrome-node
#    shm_size: "2gb"
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_SESSIONS=5
#      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
#    volumes:
#      - /dev/shm:/dev/shm
#    restart: on-failure:3
#
#  firefox:
#    image: selenium/node-firefox:4.30.0
#    container_name: firefox-node
#    shm_size: "2gb"
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_SESSIONS=5
#    volumes:
#      - /dev/shm:/dev/shm
#    restart: on-failure:3
